config/routes.rb
PatientList::Application.routes.draw do
  resources :patients

  resources :doctors

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :patients
 
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :doctor
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors }
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.json
  def new
    @doctor = Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render json: @doctor, status: :created, location: @doctor }
      else
        format.html { render action: "new" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors/1
  # PUT /doctors/1.json
  def update
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      if @doctor.update_attributes(params[:doctor])
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_form.html.haml
= form_for @doctor do |f|
  - if @doctor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@doctor.errors.count, "error")} prohibited this doctor from being saved:"
      %ul
        - @doctor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :address
    = f.text_area :address
  .actions
    = f.submit 'Save'

app/views/doctors/edit.html.haml
%h1 Editing doctor

= render 'form'

= link_to 'Show', @doctor
\|
= link_to 'Back', doctors_path

app/views/doctors/index.html.haml
%h1 Listing doctors

%table
  %tr
    %th Name
    %th Email
    %th Address
    %th Number of Patients
    %th
    %th

  - @doctors.each do |doctor|
    %tr
      %td= doctor.name
      %td= doctor.email
      %td= doctor.address
      %td= doctor.patients.count
      %td= link_to 'Show', doctor
      %td= link_to 'Edit', edit_doctor_path(doctor)
      %td= link_to 'Destroy', doctor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Doctor', new_doctor_path

app/views/doctors/new.html.haml
%h1 New doctor

= render 'form'

= link_to 'Back', doctors_path

app/views/doctors/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @doctor.name
%p
  %b Email:
  = @doctor.email
%p
  %b Address:
  = @doctor.address

%h2 Patients

%ul
  -@doctor.patients.each do |patient|
    %li
      /= patient.name
      The name is #{patient.name} the email is #{patient.email}




= link_to 'Edit', edit_doctor_path(@doctor)
\|
= link_to 'Back', doctors_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatientList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.haml
= form_for @patient do |f|
  - if @patient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@patient.errors.count, "error")} prohibited this patient from being saved:"
      %ul
        - @patient.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :doctor
    = f.collection_select :doctor_id, Doctor.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/patients/edit.html.haml
%h1 Editing patient

= render 'form'

= link_to 'Show', @patient
\|
= link_to 'Back', patients_path

app/views/patients/index.html.haml
%h1 Listing patients

%table
  %tr
    %th Name
    %th Email
    %th Doctor
    %th
    %th
    %th

  - @patients.each do |patient|
    %tr
      %td= patient.name
      %td= patient.email
      %td= patient.doctor.name
      %td= link_to 'Show', patient
      %td= link_to 'Edit', edit_patient_path(patient)
      %td= link_to 'Destroy', patient, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Patient', new_patient_path

app/views/patients/new.html.haml
%h1 New patient

= render 'form'

= link_to 'Back', patients_path

app/views/patients/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @patient.name
%p
  %b Email:
  = @patient.email
%p
  %b Doctor:
  = @patient.doctor.name

= link_to 'Edit', edit_patient_path(@patient)
\|
= link_to 'Back', patients_path